apiVersion: v1
kind: ConfigMap
metadata:
  name: xuanwu-exam-configmap
  namespace: xuanwu-system
data:
  config.yaml: |
    spring:
      datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql.infra:3306/xuanwu_exam?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
        username: root
        password: WeCoding@2023
    server:
      port: 8080
