apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xuanwu-exam
  name: xuanwu-exam
  namespace: xuanwu-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xuanwu-exam
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xuanwu-exam
        app.kubernetes.io/instance: xuanwu
    spec:
      imagePullSecrets:
        - name: "coding-registry"
      serviceAccountName: xuanwu-exam
      containers:
        - image: "image"
          imagePullPolicy: Always
          name: exam
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: WECODING_CLIENT_APIBASE
              value: "http://iam-apiserver-service.iam-system:8000"
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
          - mountPath: "/xuanwu/config.yaml"
            name: "xuanwu-exam"
            readOnly: false
            subPath: "config.yaml"
      volumes:
        - configMap:
            defaultMode: 0777
            items:
              - key: "config.yaml"
                path: "config.yaml"
            name: "xuanwu-exam-configmap"
          name: "xuanwu-exam"
