apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xuanwu-exam
  namespace: xuanwu-system
spec:
  rules:
    - host: exam.micromoving.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xuanwu-exam
                port:
                  number: 6789
