apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xuanwu-exam
  namespace: xuanwu-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
spec:
  rules:
    - host: exam.xuanwu.wecoding.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xuanwu-exam
                port:
                  number: 8080
