images:
  - name: image
    newName: docker.cnb.cool/micromoving/xuanwu/xuanwu-exam
    newTag: latest
resources:
  - ingress.yml
  - service.yml
  - service_lb.yml
  - configmap.yml
  - deployment.yml
  - rbac.yml
