apiVersion: v1
kind: Service
metadata:
  labels:
    app: xuanwu-exam
  name: xuanwu-exam-lb
  namespace: xuanwu-system
spec:
  ports:
    - name: http
      port: 6789
      protocol: TCP
      targetPort: 6789
  selector:
    app: xuanwu-exam
  type: LoadBalancer
