spring:
  application:
    name: @artifactId@
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  threads:
    virtual:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.64.5:3306/exam?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
    username: root
    password: WeCoding@2023
  flyway:
    enabled: true
    encoding: UTF-8
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: db/migration
  mvc:
    apiversion:
      use:
        path-segment: 0
      supported:
        - 1

server:
  port: 6789
  servlet:
    context-path: /
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024
  tomcat:
    keep-alive-timeout: 60s
    max-keep-alive-requests: 100
    accesslog:
      enabled: true
      buffered: true
      directory: logs/
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i" %D ms'
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
